import type { User, Class, CalendarEvent, Assignment, AttendanceRecord, Notification } from '../types';
import { addDays, subDays, format } from 'date-fns';

const today = new Date();
const fmt = (d: Date) => format(d, 'yyyy-MM-dd');

// ─── Users ────────────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Carlos Mendoza',
    email: 'admin@edusync.app',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    lastLogin: new Date(),
    classIds: [],
    phone: '+34 600 123 456',
    bio: 'Director del sistema EduSync. Gestiona la plataforma y los usuarios.',
  },
  {
    id: 'teacher-1',
    name: 'Ana García',
    email: 'ana.garcia@edusync.app',
    role: 'teacher',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    lastLogin: subDays(today, 1),
    classIds: ['class-1', 'class-2'],
    phone: '+34 611 234 567',
    bio: 'Profesora de Matemáticas y Física con 10 años de experiencia.',
  },
  {
    id: 'teacher-2',
    name: 'Roberto Sanz',
    email: 'roberto.sanz@edusync.app',
    role: 'teacher',
    status: 'active',
    createdAt: new Date('2024-02-10'),
    lastLogin: subDays(today, 3),
    classIds: ['class-3'],
    phone: '+34 622 345 678',
    bio: 'Profesor de Historia y Geografía.',
  },
  {
    id: 'student-1',
    name: 'Laura Martínez',
    email: 'laura@edusync.app',
    role: 'student',
    status: 'active',
    createdAt: new Date('2024-03-01'),
    lastLogin: today,
    classIds: ['class-1', 'class-3'],
    bio: 'Estudiante de 2º de Bachillerato.',
  },
  {
    id: 'student-2',
    name: 'Diego Fernández',
    email: 'diego@edusync.app',
    role: 'student',
    status: 'active',
    createdAt: new Date('2024-03-01'),
    lastLogin: subDays(today, 2),
    classIds: ['class-1', 'class-2'],
    bio: 'Estudiante de 2º de Bachillerato.',
  },
  {
    id: 'student-3',
    name: 'Sofía Romero',
    email: 'sofia@edusync.app',
    role: 'student',
    status: 'active',
    createdAt: new Date('2024-03-05'),
    lastLogin: subDays(today, 1),
    classIds: ['class-1'],
    bio: 'Estudiante de 2º de Bachillerato.',
  },
  {
    id: 'student-4',
    name: 'Marcos Jiménez',
    email: 'marcos@edusync.app',
    role: 'student',
    status: 'blocked',
    createdAt: new Date('2024-03-05'),
    lastLogin: subDays(today, 10),
    classIds: ['class-2'],
    bio: 'Estudiante de 1º de Bachillerato.',
  },
];

// ─── Classes ──────────────────────────────────────────────────────────────────
export const MOCK_CLASSES: Class[] = [
  {
    id: 'class-1',
    name: '2º Bach A — Matemáticas',
    subject: 'Matemáticas',
    description: 'Matemáticas de 2º de Bachillerato, grupo A. Álgebra, cálculo y estadística.',
    teacherId: 'teacher-1',
    studentIds: ['student-1', 'student-2', 'student-3'],
    code: 'MAT2A-7X4',
    createdAt: new Date('2024-09-01'),
    schedule: 'Lun/Mié/Vie 09:00–10:00',
    room: 'Aula 204',
    color: '#3b82f6',
    isArchived: false,
  },
  {
    id: 'class-2',
    name: '1º Bach B — Física',
    subject: 'Física',
    description: 'Física de 1º de Bachillerato, grupo B. Mecánica, termodinámica y electromagnetismo.',
    teacherId: 'teacher-1',
    studentIds: ['student-2', 'student-4'],
    code: 'FIS1B-9K2',
    createdAt: new Date('2024-09-01'),
    schedule: 'Mar/Jue 11:00–12:30',
    room: 'Lab. Física',
    color: '#8b5cf6',
    isArchived: false,
  },
  {
    id: 'class-3',
    name: '2º Bach A — Historia',
    subject: 'Historia de España',
    description: 'Historia de España contemporánea para 2º de Bachillerato.',
    teacherId: 'teacher-2',
    studentIds: ['student-1'],
    code: 'HIS2A-3M8',
    createdAt: new Date('2024-09-01'),
    schedule: 'Lun/Jue 12:00–13:00',
    room: 'Aula 101',
    color: '#10b981',
    isArchived: false,
  },
];

// ─── Events ───────────────────────────────────────────────────────────────────
export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Examen Parcial — Álgebra',
    description: 'Examen de los temas 1–4: sistemas de ecuaciones, matrices y determinantes.',
    date: fmt(addDays(today, 5)),
    startTime: '09:00',
    endTime: '10:30',
    type: 'exam',
    classId: 'class-1',
    createdBy: 'teacher-1',
    recurrence: 'none',
    reminder: 1440,
    color: '#ef4444',
  },
  {
    id: 'evt-2',
    title: 'Entrega Práctica — Cinemática',
    description: 'Entrega del informe de la práctica de laboratorio sobre movimiento rectilíneo.',
    date: fmt(addDays(today, 3)),
    startTime: '11:00',
    endTime: '11:00',
    type: 'assignment',
    classId: 'class-2',
    createdBy: 'teacher-1',
    recurrence: 'none',
    reminder: 60,
    color: '#f59e0b',
  },
  {
    id: 'evt-3',
    title: 'Clase — Integrales',
    description: 'Introducción al cálculo integral y técnicas de integración.',
    date: fmt(today),
    startTime: '09:00',
    endTime: '10:00',
    type: 'class',
    classId: 'class-1',
    createdBy: 'teacher-1',
    recurrence: 'weekly',
    color: '#3b82f6',
  },
  {
    id: 'evt-4',
    title: 'Reunión de Departamento',
    description: 'Reunión mensual del departamento de Ciencias.',
    date: fmt(addDays(today, 7)),
    startTime: '14:00',
    endTime: '15:30',
    type: 'meeting',
    createdBy: 'teacher-1',
    recurrence: 'monthly',
    color: '#6366f1',
  },
  {
    id: 'evt-5',
    title: 'Festivo — Día de la Constitución',
    date: fmt(addDays(today, 12)),
    type: 'holiday',
    createdBy: 'admin-1',
    recurrence: 'none',
    color: '#64748b',
  },
  {
    id: 'evt-6',
    title: 'Control — Segunda Guerra Mundial',
    description: 'Control escrito sobre los temas 6 y 7.',
    date: fmt(addDays(today, 10)),
    startTime: '12:00',
    endTime: '13:00',
    type: 'exam',
    classId: 'class-3',
    createdBy: 'teacher-2',
    recurrence: 'none',
    reminder: 1440,
    color: '#ef4444',
  },
  {
    id: 'evt-7',
    title: 'Clase — Termodinámica',
    date: fmt(subDays(today, 2)),
    startTime: '11:00',
    endTime: '12:30',
    type: 'class',
    classId: 'class-2',
    createdBy: 'teacher-1',
    recurrence: 'none',
    color: '#8b5cf6',
  },
  {
    id: 'evt-8',
    title: 'Tutoría Individual',
    description: 'Tutoría con Laura Martínez sobre el examen de recuperación.',
    date: fmt(addDays(today, 2)),
    startTime: '13:00',
    endTime: '13:30',
    type: 'meeting',
    classId: 'class-1',
    createdBy: 'teacher-1',
    recurrence: 'none',
    color: '#6366f1',
  },
];

// ─── Assignments ──────────────────────────────────────────────────────────────
export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: 'assign-1',
    title: 'Ejercicios de Matrices — Hoja 3',
    description: 'Resolver los ejercicios del 15 al 30 de la hoja de problemas número 3. Mostrar todos los pasos.',
    classId: 'class-1',
    createdBy: 'teacher-1',
    dueDate: fmt(addDays(today, 5)),
    maxScore: 10,
    attachments: [],
    submissions: [
      { id: 'sub-1', assignmentId: 'assign-1', studentId: 'student-1', status: 'submitted', submittedAt: subDays(today, 1), attachments: [] },
      { id: 'sub-2', assignmentId: 'assign-1', studentId: 'student-2', status: 'pending', attachments: [] },
      { id: 'sub-3', assignmentId: 'assign-1', studentId: 'student-3', status: 'pending', attachments: [] },
    ],
    createdAt: subDays(today, 7),
  },
  {
    id: 'assign-2',
    title: 'Informe — Práctica de Laboratorio',
    description: 'Redactar un informe completo sobre el experimento de cinemática realizado en el laboratorio. Incluir introducción, metodología, resultados y conclusiones.',
    classId: 'class-2',
    createdBy: 'teacher-1',
    dueDate: fmt(addDays(today, 3)),
    maxScore: 10,
    attachments: [],
    submissions: [
      { id: 'sub-4', assignmentId: 'assign-2', studentId: 'student-2', status: 'graded', score: 8.5, submittedAt: subDays(today, 2), feedback: 'Excelente análisis. Mejora la presentación de los datos.', attachments: [] },
    ],
    createdAt: subDays(today, 10),
  },
  {
    id: 'assign-3',
    title: 'Ensayo — Causas de la Primera Guerra Mundial',
    description: 'Escribe un ensayo argumentativo de entre 500 y 800 palabras sobre las causas principales de la Primera Guerra Mundial.',
    classId: 'class-3',
    createdBy: 'teacher-2',
    dueDate: fmt(addDays(today, 8)),
    maxScore: 10,
    attachments: [],
    submissions: [
      { id: 'sub-5', assignmentId: 'assign-3', studentId: 'student-1', status: 'pending', attachments: [] },
    ],
    createdAt: subDays(today, 3),
  },
];

// ─── Attendance ───────────────────────────────────────────────────────────────
export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    classId: 'class-1',
    date: fmt(subDays(today, 2)),
    records: [
      { studentId: 'student-1', present: true },
      { studentId: 'student-2', present: true },
      { studentId: 'student-3', present: false, note: 'Justificada' },
    ],
    createdBy: 'teacher-1',
  },
  {
    id: 'att-2',
    classId: 'class-1',
    date: fmt(subDays(today, 5)),
    records: [
      { studentId: 'student-1', present: true },
      { studentId: 'student-2', present: false },
      { studentId: 'student-3', present: true },
    ],
    createdBy: 'teacher-1',
  },
  {
    id: 'att-3',
    classId: 'class-2',
    date: fmt(subDays(today, 3)),
    records: [
      { studentId: 'student-2', present: true },
      { studentId: 'student-4', present: false, note: 'Sin justificar' },
    ],
    createdBy: 'teacher-1',
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'student-1',
    title: 'Nuevo examen programado',
    message: 'Se ha programado un examen de Álgebra para el ' + format(addDays(today, 5), 'dd/MM/yyyy'),
    type: 'warning',
    read: false,
    createdAt: subDays(today, 1),
  },
  {
    id: 'notif-2',
    userId: 'student-1',
    title: 'Tarea calificada',
    message: 'Tu práctica de laboratorio ha sido calificada con 8.5/10.',
    type: 'success',
    read: false,
    createdAt: subDays(today, 2),
  },
  {
    id: 'notif-3',
    userId: 'teacher-1',
    title: 'Nueva entrega recibida',
    message: 'Laura Martínez ha enviado los ejercicios de matrices.',
    type: 'info',
    read: true,
    createdAt: subDays(today, 1),
  },
  {
    id: 'notif-4',
    userId: 'teacher-1',
    title: 'Recordatorio de evento',
    message: 'Reunión de departamento mañana a las 14:00.',
    type: 'info',
    read: false,
    createdAt: today,
  },
  {
    id: 'notif-5',
    userId: 'admin-1',
    title: 'Nuevo usuario registrado',
    message: 'Sofía Romero se ha registrado en la plataforma.',
    type: 'info',
    read: false,
    createdAt: subDays(today, 1),
  },
];

// ─── Passwords (simulated) ─────────────────────────────────────────────────────
// In production these would be hashed. For demo we use plain map.
export const MOCK_PASSWORDS: Record<string, string> = {
  'admin@edusync.app': 'Admin1234!',
  'ana.garcia@edusync.app': 'Profe1234!',
  'roberto.sanz@edusync.app': 'Profe1234!',
  'laura@edusync.app': 'Alumno1234!',
  'diego@edusync.app': 'Alumno1234!',
  'sofia@edusync.app': 'Alumno1234!',
  'marcos@edusync.app': 'Alumno1234!',
};
